In [1]:
import pandas as pd

In [2]:
from sklearn.datasets import load_diabetes
diabetes = load_diabetes()

df = pd.DataFrame(data=diabetes.data, columns=diabetes.feature_names)

In [3]:
df
df.info()
df.corr()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     442 non-null    float64
 1   sex     442 non-null    float64
 2   bmi     442 non-null    float64
 3   bp      442 non-null    float64
 4   s1      442 non-null    float64
 5   s2      442 non-null    float64
 6   s3      442 non-null    float64
 7   s4      442 non-null    float64
 8   s5      442 non-null    float64
 9   s6      442 non-null    float64
dtypes: float64(10)
memory usage: 34.7 KB

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
count,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02
mean,-2.511817e-19,1.230790e-17,-2.245564e-16,-4.797570e-17,-1.381499e-17,3.918434e-17,-5.777179e-18,-9.042540e-18,9.293722e-17,1.130318e-17
std,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02
min,-1.072256e-01,-4.464164e-02,-9.027530e-02,-1.123988e-01,-1.267807e-01,-1.156131e-01,-1.023071e-01,-7.639450e-02,-1.260971e-01,-1.377672e-01
25%,-3.729927e-02,-4.464164e-02,-3.422907e-02,-3.665608e-02,-3.424784e-02,-3.035840e-02,-3.511716e-02,-3.949338e-02,-3.324559e-02,-3.317903e-02
50%,5.383060e-03,-4.464164e-02,-7.283766e-03,-5.670422e-03,-4.320866e-03,-3.819065e-03,-6.584468e-03,-2.592262e-03,-1.947171e-03,-1.077698e-03
75%,3.807591e-02,5.068012e-02,3.124802e-02,3.564379e-02,2.835801e-02,2.984439e-02,2.931150e-02,3.430886e-02,3.243232e-02,2.791705e-02
max,1.107267e-01,5.068012e-02,1.705552e-01,1.320436e-01,1.539137e-01,1.987880e-01,1.811791e-01,1.852344e-01,1.335973e-01,1.356118e-01

In [4]:
X = df.drop(columns='s6')
y = df['s6']
X,y

(          age       sex       bmi        bp        s1        s2        s3  \
 0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401
 1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412
 2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356
 3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038
 4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142
 ..        ...       ...       ...       ...       ...       ...       ...
 437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674
 438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674
 439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993
 440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674
 441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816

            s4        s5
 0   -0.002592  0.019907
 1   -0.039493 -0.068332
 2   -0.002592  0.002861
 3    0.034309  0.022688
 4   -0.002592 -0.031988
 ..        ...       ...
 437 -0.002592  0.031193
 438  0.034309 -0.018114
 439 -0.011080 -0.046883
 440  0.026560  0.044529
 441 -0.039493 -0.004222

 [442 rows x 9 columns],
 0     -0.017646
 1     -0.092204
 2     -0.025930
 3     -0.009362
 4     -0.046641
          ...
 437    0.007207
 438    0.044485
 439    0.015491
 440   -0.025930
 441    0.003064
 Name: s6, Length: 442, dtype: float64)

In [5]:
from sklearn.model_selection import train_test_split

#Create Train And Test DAta
X_train, X_test,y_train,y_test = train_test_split(X, y, test_size = 0.2)

X_train

,age,sex,bmi,bp,s1,s2,s3,s4,s5
116,0.048974,0.050680,0.058463,0.070072,0.013567,0.020607,-0.021311,0.034309,0.022004
126,-0.089063,-0.044642,-0.061174,-0.026328,-0.055231,-0.054549,0.041277,-0.076395,-0.093937
157,-0.001882,0.050680,-0.033151,-0.018306,0.031454,0.042840,-0.013948,0.019917,0.010227
24,-0.063635,-0.044642,0.035829,-0.022885,-0.030464,-0.018850,-0.006584,-0.002592,-0.025953
50,0.034443,-0.044642,-0.007284,0.014987,-0.044223,-0.037326,-0.002903,-0.039493,-0.021395
...,...,...,...,...,...,...,...,...,...
236,0.027178,-0.044642,0.006728,0.035644,0.079612,0.070710,0.015505,0.034309,0.040673
130,-0.063635,0.050680,0.096186,0.104501,-0.002945,-0.004759,-0.006584,-0.002592,0.022688
239,0.023546,-0.044642,0.019662,-0.012556,0.083740,0.038769,0.063367,-0.002592,0.066051
149,-0.049105,0.050680,-0.005128,-0.046985,-0.020832,-0.020416,-0.069172,0.071210,0.061238
313,0.059871,0.050680,0.053074,0.052858,0.032830,0.019667,-0.010266,0.034309,0.055203

In [6]:
#Ridge
from sklearn.linear_model import Ridge
ridge_model = Ridge(alpha = 0.1)
ridge_model.fit(X_train, y_train)
ridge_model.coef_

array([0.08304533, 0.06294955, 0.14109608, 0.14801431, 0.03920542,
       0.03065619, 0.01052116, 0.13571259, 0.16781536])

In [7]:
y_predicted = ridge_model.predict(X_test)
y_predicted

array([ 7.73349026e-03, -5.09649465e-02, -2.13564400e-02, -2.39030107e-02,
        3.07935549e-02, -3.15512339e-02,  2.44266974e-02,  1.35034359e-03,
        1.55463402e-02, -2.38218094e-03, -2.58026379e-02,  1.34296032e-02,
       -3.18340573e-02, -2.89698416e-02,  1.65885467e-02,  6.88028481e-03,
       -1.45518237e-02,  2.44312071e-02,  2.22785128e-02,  3.42873250e-02,
        1.60505192e-02, -8.58631771e-03, -3.47177883e-02,  2.82228898e-02,
       -2.47695177e-02,  1.90072195e-02, -1.90077882e-05, -1.10642550e-02,
        2.84822372e-02, -5.07178674e-03,  2.32765266e-02,  1.34586899e-02,
       -1.64386807e-02, -2.05733846e-02,  1.06397790e-02,  4.02619668e-02,
        4.94716588e-02, -1.29732969e-02,  2.45135460e-02, -5.47595995e-03,
       -2.14801267e-02,  4.65954653e-02,  1.46689346e-02, -4.30719263e-02,
       -1.83683474e-02, -2.42297379e-02,  2.08378001e-02, -1.91981906e-02,
       -6.99164847e-03,  8.38756714e-03,  5.05461321e-02, -4.29375048e-02,
       -3.23227104e-02,  3.45223611e-02, -2.57487238e-02, -3.67828005e-02,
       -1.16783411e-02,  4.32832845e-02,  3.24616376e-02,  1.72806084e-02,
       -3.25289491e-02, -1.65778335e-02,  2.86642827e-02,  3.29997141e-02,
       -1.98429398e-02, -1.57191120e-02, -4.51133412e-03, -2.85960732e-02,
        2.51692144e-02,  2.28261112e-03,  2.70381591e-02,  4.20172320e-02,
       -3.62829837e-02, -2.67945796e-02, -2.14857187e-02,  5.01838150e-03,
        3.65666769e-02,  8.64697169e-03,  1.48794064e-02, -3.70613483e-02,
        2.18806091e-02,  5.15770218e-03, -1.83087964e-02, -2.08518415e-02,
       -5.00835995e-02, -4.39549692e-02, -6.47847631e-03,  2.37745246e-02,
       -1.76086497e-02])

In [8]:
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, mean_squared_error, r2_score

ridge_mae = mean_absolute_error(y_predicted, y_test)
ridge_mse = mean_squared_error(y_predicted, y_test)
ridge_rmse = root_mean_squared_error(y_predicted, y_test)

ridge_mae, ridge_mse, ridge_rmse

(0.030721874785211045, 0.0013605698362778263, 0.03688590294784481)